# Generated by Django 5.0.1 on 2024-01-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
