# Generated by Django 5.0.1 on 2024-01-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='number',
        ),
    ]
