# Generated by Django 5.0.1 on 2024-01-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
