# Generated by Django 5.0.1 on 2024-01-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Edu',
        ),
        migrations.AlterModelOptions(
            name='edu',
            options={'verbose_name': 'Edu', 'verbose_name_plural': 'Edus'},
        ),
    ]
