# Generated by Django 5.0.1 on 2024-01-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_img_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
    ]
