# Generated by Django 5.0.1 on 2024-01-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_complate_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
